name: scribe
description: A simple recording and transcription app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  record: 
    git: 
      url: https://github.com/llfbandit/record.git
      ref: 89e401ebc64cf83dd5c755b230bd22cb15453f07
      path: record
  intl: ^0.18.1
  go_router: ^10.1.0
  sqflite: ^2.3.0
  flutter_mobx: ^2.0.6
  mobx: ^2.2.0
  file_picker: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  ffigen: ^9.0.1
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0

ffigen:
  output: 'lib/whisper_generated.dart'
  headers:
    entry-points:
      - '../whisper/bindings.h'
  # On MacOS
  llvm-path:
    - '/opt/homebrew/Cellar/llvm/16.0.6'

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
