name: scribe
description: A simple recording and transcription app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  record: ^4.4.4
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  ffigen: ^9.0.1

ffigen:
  output: 'lib/whisper_generated.dart'
  headers:
    entry-points:
      - '../whisper/bindings.h'
  # On MacOS
  llvm-path:
    - '/opt/homebrew/Cellar/llvm/16.0.6'

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
